import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		double average=0, sum=0; 
		int girlCounter=0, boyCounter=0, total=0;
		int twokids=0,threekids=0,fourkids=0;
		double gender=0;
		for(int i=0; i<T; i++){
		while((girlCounter<1)||(boyCounter<1)){
			gender=generator.nextDouble();
			if(gender <0.5){
				girlCounter++;
			}	
			else{
				boyCounter++;
			}
			total++;
		}
			sum = sum+total;
			
			if(total == 2){
				twokids++;
			}
			else if(total == 3){
				threekids++;
			}
			else{
				fourkids++;
			}
			
			total = 0;
			girlCounter = 0;
			boyCounter = 0;
			
		}
		average= (double)sum/(double)T;
		System.out.println("Average: " +average+" children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " +twokids);
		System.out.println("Number of families with 3 children: " +threekids);
		System.out.println("Number of families with 4 or more children: " +fourkids);
		if((twokids>threekids)&&(twokids>=fourkids)){
			System.out.println("The most common number of children is 2.");
		}
		else if((threekids>=twokids)&&(threekids>fourkids)){
			System.out.println("The most common number of children is 3.");
		}
		else{
			System.out.println("The most common number of children is 4 or more.");
		}
		
		    
	}
}