import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
				double average; 
		int girlCounter=0, boyCounter=0, total=0, sum=0;
		int twokids=0,threekids=0,fourkids=0;
		int n = Integer.parseInt(args[0]);
		for(int i=0; i<n; i++){
		while((girlCounter<1)||(boyCounter<1)){
			int gender=generator.nextInt();
			if(gender <=4){
				girlCounter++;
			}	
			else{
				boyCounter++;
			}
			total++;
		}
			sum = sum+total;
			
			if(total == 2){
				twokids++;
			}
			else if(total == 3){
				threekids++;
			}
			else{
				fourkids++;
			}
			
			total = 0;
			girlCounter = 0;
			boyCounter = 0;
			
		}
		average= (double)sum/(double)n;
		System.out.println("Average: " +average+" children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " +twokids);
		System.out.println("Number of families with 3 children: " +threekids);
		System.out.println("Number of families with 4 or more children: " +fourkids);
		if((twokids>threekids)&&(twokids>=fourkids)){
			System.out.println("The most common number of children is 2.");
		}
		else if((threekids>=twokids)&&(threekids>fourkids)){
			System.out.println("The most common number of children is 3.");
		}
		else{
			System.out.println("The most common number of children is 4 or more.");
		}
		
		
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}